Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')
src     = Glob('*.c')
src    += Glob('ccsds/*.c')
CPPPATH = [cwd, os.path.join(cwd, 'ccsds'), str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
