#!/bin/sh

# Mount filesystems
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t tmpfs tmpfs /tmp
/bin/mount -t tmpfs tmpfs /var

# Start mdev (dynamic device manager)
/sbin/mdev -s

# Set hostname
/bin/hostname -F /etc/hostname

# Load SX1262 kernel module
/sbin/insmod /lib/modules/5.10.160/sx1262.ko

# Load ICM-42670-P IMU kernel module
/sbin/insmod /lib/modules/5.10.160/icm42670.ko
